### ISSUE TITLE
Let result.get() return a Result or provide some other way to use the get() function on sub dicts.

### ISSUE THREAD

**Issue by tru** [kwk/ghgql#5]
If you have a complex result it can be annoying to get information out from the looped dictionaries:

```
for node in data.get("organization.projectV2.items.nodes", default=[]):
  // Here I want get "content.milestone.number"
  // If we change get() to return Result you can do this:
  node.get("content.milestone.number")
  // Otherwise I have to do something like this:
  node["content"]["milestone"]["number"]
```

**Comment by kwk** [comment]
> If you have a complex result it can be annoying to get information out from the looped dictionaries:

@tru, I understand and as of v1.0.0 which should land soon you there no longer is the need for the `Result` class at all. I've discovered that this works much smoother:

```python
import fnc

with ghgql.GithubGraphQL(token="YOUR_TOKEN") as ghapi:
    result = ghapi.query(query=query, variables={"org": "YOUR_ORG", "number": "YOUR_REPO"})

    # Get the array you wanted. NOTE, that "data." has to be part of the query now!
    nodes = fnc.get("data.organization.projectV2.items.nodes", result)

    # Get the milestone numbers by iterating like you do in your code above:
    for node in nodes:
        print(fnc.get("content.milestone.number", node))

    # Different approach: get milestone numbers with the `map` function.
    milestone_numbers = fnc.map("content.milestone.number", nodes)

```

> ```python
>   // If we change get() to return Result you can do this:
>   node.get("content.milestone.number")
>   // Otherwise I have to do something like this:
>   node["content"]["milestone"]["number"]
> ```

That is correct. This issue is really two-fold:

1. A feature request for more convenience
2. A proposal for how to get there

I think that as of v1.0.0 the convenience part is achieved but with a different approach, hence I want to close this issue. Are you fine with this?

**Comment by tru** [comment]
Yeah this seems fine to me. The dependency is not a huge issue - I'll give this a try as soon as I have time!
